spring.application.name=back-sesion
# Puerto de la app
server.port=8080

# Reemplaza la linea jdbc:h2:mem... por esta en AMBOS proyectos:
spring.datasource.url=jdbc:h2:file:./data/banco_cloud_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true