spring.application.name=back-sesion
# Puerto de la app
server.port=8080

# Configuración de base de datos en memoria H2
spring.datasource.url=jdbc:h2:mem:banco_cloud
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate configurado para H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Habilitar la consola web de H2 para que puedas ver tus tablas
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console