spring.application.name=back-sesion
server.port=8081

# Conexión a AWS RDS MySQL
spring.datasource.url=jdbc:mysql://banco-cloud-db.cmggybjdfvmj.us-east-1.rds.amazonaws.com:3306/banco_cloud_db
spring.datasource.username=admin
spring.datasource.password=the67mastercrack
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate para MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true